# site settings
title: Sport Faces
subtitle:
email: info@robbertenfrank.com
description: Een project in het kader van Kortrijk Europese Sportstad 2018 <br/>Frank&Robbert Robbert&Frank i.s.m. Buda VZW, Bubox en Stad Kortrijk.
baseurl: "/sportfaceskortrijk" # the subpath of your site, e.g. /blog
url: "www.sportfaces.be" # the base hostname & protocol for your siteauthor: Robbert&Frank Frank&Robbert
street_address:
city:
state:
zip_code:
country: Belgium
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: http://www.facebook.com/frankenrobbertrobbertenfrank
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/sportfaces_kortrijk
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
